# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_prime <- function(x) {
    .Call(`_StatsChitran_is_prime`, x)
}

is_prime_large <- function(X) {
    .Call(`_StatsChitran_is_prime_large`, X)
}

is_prime_par <- function(N) {
    .Call(`_StatsChitran_is_prime_par`, N)
}

movavg_cpp <- function(Y, bn, fn, ord) {
    .Call(`_StatsChitran_movavg_cpp`, Y, bn, fn, ord)
}

prime_firstN <- function(n) {
    .Call(`_StatsChitran_prime_firstN`, n)
}

