# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_prime <- function(x) {
    .Call(`_StatsChitran_is_prime`, x)
}

prime_firstN <- function(n) {
    .Call(`_StatsChitran_prime_firstN`, n)
}

