# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RSum_par <- function(X, Y, xmin, xmax) {
    .Call(`_StatsChitran_RSum_par`, X, Y, xmin, xmax)
}

num_integrate_cpp <- function(X, Y, xmin, xmax) {
    .Call(`_StatsChitran_num_integrate_cpp`, X, Y, xmin, xmax)
}

RSum <- function(X, Y, xmin, xmax) {
    .Call(`_StatsChitran_RSum`, X, Y, xmin, xmax)
}

is_prime <- function(x) {
    .Call(`_StatsChitran_is_prime`, x)
}

is_prime_large <- function(X) {
    .Call(`_StatsChitran_is_prime_large`, X)
}

is_prime_par <- function(N) {
    .Call(`_StatsChitran_is_prime_par`, N)
}

movavg_cpp <- function(Y, bn, fn, ord) {
    .Call(`_StatsChitran_movavg_cpp`, Y, bn, fn, ord)
}

num_integrate_par <- function(X, Y, xmin, xmax) {
    .Call(`_StatsChitran_num_integrate_par`, X, Y, xmin, xmax)
}

prime_firstN <- function(n) {
    .Call(`_StatsChitran_prime_firstN`, n)
}

